### PR TITLE
pbkdf2: bump `crypto-mac` dependency to v0.9

### PR DESCRIPTION
**Pull request by tarcieri**

### CODE REVIEW

**Comment by newpavlov** [comment]
I think it would be nice to bump `pbkdf2` minor version, update the dependent crates and cut releases directly after merging this PR.

**Comment by tarcieri** [comment]
@newpavlov yup, that's the plan. We need to do `scrypt` too, as it depends on `pbkdf2`.

**Comment by newpavlov** [comment]
I meant as part of this PR, but oh well. :)

**Comment by tarcieri** [comment]
Aah, oh well! Preparing a follow-up PR now.

**Pull request merged**
